[package]
name = "AqooleEngineR"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
bindgen = "0.69.1"
anyhow = "1"
log = "0.4"
cgmath = "0.18"
png = "0.17"
pretty_env_logger = "0.4"
thiserror = "1"
tobj = { version = "3", features = ["log"] }
vulkanalia = { version = "=0.26.0", features = ["libloading", "provisional", "window"] }
copypasta = "0.8"
glutin = "0.31.1"
glutin-winit = "0.4.2"
imgui = { path = "./src/imgui", features = ["tables-api"] }
imgui-glium-renderer = { path = "./src/imgui-glium-renderer" }
imgui-winit-support = { path = "./src/imgui-winit-support" }
glium = "*"

[dependencies.gltf]
version = "1.4"
features = ["extras", "names"]

[build-dependencies]
bindgen = "0.69.1"
cxx-build = "1.0"