#version 460
#extension GL_EXT_ray_tracing : require

layout(set = 0, binding = 0) uniform accelerationStructureEXT tlas;
layout(set = 0, binding = 1, rgba16f) uniform image2D outImage;
layout(location = 0) rayPayloadEXT vec4 payload;

void main() {
   traceRayEXT(tlas, gl_RayFlagsOpaqueEXT, 0xff, 0, 0, 0, vec3(0.0), 0.0, vec3(0.0, -1.0, 0.0), 1e30, 0);
    imageStore(outImage, ivec2(gl_LaunchIDEXT.xy), payload);
}
