"""Build capability flags derived from ``BUILD_MODE``.

``build_config.py`` is generated by ``scripts/build_blender_addon.{sh,ps1}``
(``--build-mode A|B|C``; definition SSoT: crates/thyllore-ml-core/src/mode.rs)
and is the single source of truth for the distribution mode. Everything
mode-dependent (telemetry availability, license activation, free-text message
channel) is derived here and nowhere else. The effective context length
(32/64) is NOT decided here -- the ``thyllore_ml_core`` wheel decides it from
the full token.

Source-tree runs (no generated ``build_config.py``) behave like mode A with
no endpoints: no telemetry, no license activation, no message channel.
"""
from __future__ import annotations

from enum import Enum

try:
    from . import build_config
except ImportError:
    build_config = None

BUILD_MODE = getattr(build_config, "BUILD_MODE", "A")
FEEDBACK_ENDPOINT = getattr(build_config, "FEEDBACK_ENDPOINT", "")
INGEST_TOKEN = getattr(build_config, "INGEST_TOKEN", "")


class BuildMode(Enum):
    OFFICIAL = "A"
    STATIC = "B"
    MARKET = "C"


class Capabilities:
    def __init__(self, mode: BuildMode):
        self.mode = mode
        self.telemetry_available = mode is BuildMode.STATIC
        self.license_activation = mode is BuildMode.MARKET
        self.message_available = bool(FEEDBACK_ENDPOINT and INGEST_TOKEN)

    @classmethod
    def from_build(cls) -> "Capabilities":
        return cls(BuildMode(BUILD_MODE))


CAPS = Capabilities.from_build()
