"""Build capability flags derived from ``BUILD_MODE``.

``build_config.py`` is generated by ``scripts/build_blender_addon.{sh,ps1}``
(``--build-mode A|B|C``; definition SSoT: crates/thyllore-ml-core/src/mode.rs)
and is the single source of truth for the distribution mode. Everything
mode-dependent (telemetry availability, free-text message channel, the wheel
mode string) is derived here and nowhere else. The effective context length
(32/64) is NOT decided here -- the ``thyllore_ml_core`` wheel decides it from
``curve_copilot_mode`` plus (mode B only) the full token.

Modes A and C ship no network code at all: the build excludes
``feedback_message.py`` and bakes no endpoints. Mode C (private, sold on
BOOTH) unlocks the full context unconditionally through the wheel's private
path. Source-tree runs (no generated ``build_config.py``) behave like mode A.
"""
from __future__ import annotations

from enum import Enum

try:
    from . import build_config
except ImportError:
    build_config = None

BUILD_MODE = getattr(build_config, "BUILD_MODE", "A")
FEEDBACK_ENDPOINT = getattr(build_config, "FEEDBACK_ENDPOINT", "")
INGEST_TOKEN = getattr(build_config, "INGEST_TOKEN", "")


class BuildMode(Enum):
    OFFICIAL = "A"
    STATIC = "B"
    PRIVATE = "C"


_CURVE_COPILOT_MODES = {
    BuildMode.OFFICIAL: "degrade",
    BuildMode.STATIC: "full",
    BuildMode.PRIVATE: "private",
}


class Capabilities:
    def __init__(self, mode: BuildMode):
        self.mode = mode
        self.telemetry_available = mode is BuildMode.STATIC
        self.message_available = mode is BuildMode.STATIC and bool(
            FEEDBACK_ENDPOINT and INGEST_TOKEN
        )
        self.curve_copilot_mode = _CURVE_COPILOT_MODES[mode]

    @classmethod
    def from_build(cls) -> "Capabilities":
        return cls(BuildMode(BUILD_MODE))


CAPS = Capabilities.from_build()
