"""Build capability flags derived from ``BUILD_MODE``.

``build_config.py`` is generated by ``scripts/build_blender_addon.{sh,ps1}``
(``--build-mode A|B|C``) and is the single source of truth for the
distribution mode. Everything mode-dependent (telemetry availability, license
activation) is derived here and nowhere else. The effective context length
(32/64) is NOT decided here -- the ``thyllore_ml_core`` wheel decides it from
the unlock token.

Source-tree runs (no generated ``build_config.py``) behave like mode A: no
telemetry, no license activation.
"""
from __future__ import annotations

from enum import Enum

try:
    from .build_config import BUILD_MODE
except ImportError:
    BUILD_MODE = "A"


class BuildMode(Enum):
    OFFICIAL = "A"
    STATIC = "B"
    MARKET = "C"


class Capabilities:
    def __init__(self, mode: BuildMode):
        self.mode = mode
        self.telemetry_available = mode is BuildMode.STATIC
        self.license_activation = mode is BuildMode.MARKET

    @classmethod
    def from_build(cls) -> "Capabilities":
        return cls(BuildMode(BUILD_MODE))


CAPS = Capabilities.from_build()
