#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCENE="$REPO_ROOT/blender/flame.blend"
PLATFORM="linux_x86_64"
REBUILD_ZIP=1
GUI_ARGS=()

usage() {
    cat <<USAGE
Usage: $0 [--skip-build] [--software-gl] [scene.blend]

Builds the flame addon ZIP (scripts/build_blender_flame_addon.sh), then
launches the pristine Blender Docker image on the NVIDIA GPU
(blender/docker/run_gui.sh) with the ZIP installed into a fresh profile,
opens the scene (default: blender/flame.blend = camera + light + one campfire,
generated by scripts/blender_make_flame_scene.py when missing) and embeds a
campfire flame if the scene has none, so the viewport draw handler can be
checked at once. Blender's console output
(including draw handler failures) is mirrored to <repo>/log/log_blender_flame.log.

Options:
  --skip-build         Reuse dist/thyllore_flame-*-$PLATFORM.zip
  --software-gl        Passed through to run_gui.sh (Mesa llvmpipe)
  -h, --help           Show this help
USAGE
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --skip-build) REBUILD_ZIP=0; shift ;;
        --software-gl) GUI_ARGS+=(--software-gl); shift ;;
        -h|--help) usage; exit 0 ;;
        *) SCENE="$1"; shift ;;
    esac
done

if [[ "$REBUILD_ZIP" -eq 1 ]]; then
    bash "$REPO_ROOT/scripts/build_blender_flame_addon.sh" --platform "$PLATFORM"
fi
ZIP="$(ls -t "$REPO_ROOT"/dist/thyllore_flame-*-"$PLATFORM".zip | head -1)"

if [[ "$SCENE" == "$REPO_ROOT/blender/flame.blend" && ! -f "$SCENE" ]]; then
    echo "[run_blender_flame] generating $SCENE"
    docker run --rm -v "$REPO_ROOT:/workspace:ro" -v "$(dirname "$ZIP"):/zips:ro" -v "$REPO_ROOT/blender:/out" thyllore-blender-smoke bash -c "
        export HOME=/tmp/blender_home && mkdir -p \"\$HOME\" &&
        blender --command extension install-file -r user_default --enable /zips/$(basename "$ZIP") >/dev/null &&
        blender -b --python-exit-code 1 --python /workspace/scripts/blender_make_flame_scene.py -- /out/flame.blend
    "
fi

LOG="$REPO_ROOT/log/log_blender_flame.log"
mkdir -p "$REPO_ROOT/log"
echo "[run_blender_flame] launching Blender (docker, NVIDIA) with $SCENE"
echo "[run_blender_flame] Blender stdout/stderr -> $LOG"
bash "$REPO_ROOT/blender/docker/run_gui.sh" \
    --zip "$ZIP" --scene "$SCENE" \
    --python "$REPO_ROOT/scripts/blender_flame_embed.py" \
    ${GUI_ARGS[@]+"${GUI_ARGS[@]}"} 2>&1 | tee "$LOG"
